# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Generator_main_.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(90, 90, 90)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Generate_button = QtWidgets.QPushButton(self.centralwidget)
        self.Generate_button.setGeometry(QtCore.QRect(70, 80, 141, 31))
        self.Generate_button.setStyleSheet("background-color: rgb(13, 13, 13);\n"
                                           "font: 63 8pt \"Bahnschrift SemiBold\";\n"
                                           "color:rgb(255, 255, 255);\n"
                                           "border-style:outset;\n"
                                           "border-width:4px;\n"
                                           "border-radius:15px;\n"
                                           "border-color:rgb(30, 30, 30)")
        self.Generate_button.setObjectName("Generate_button")
        self.Save_button = QtWidgets.QPushButton(self.centralwidget)
        self.Save_button.setGeometry(QtCore.QRect(70, 140, 141, 31))
        self.Save_button.setStyleSheet("background-color: rgb(13, 13, 13);\n"
                                       "font: 63 8pt \"Bahnschrift SemiBold\";\n"
                                       "color:rgb(255, 255, 255);\n"
                                       "border-style:outset;\n"
                                       "border-width:4px;\n"
                                       "border-radius:15px;\n"
                                       "border-color:rgb(30, 30, 30)")
        self.Save_button.setObjectName("Save_button")
        self._VERSION = QtWidgets.QLabel(self.centralwidget)
        self._VERSION.setGeometry(QtCore.QRect(10, 10, 241, 51))
        self._VERSION.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
                                    "color:rgb(255, 255, 255);")
        self._VERSION.setObjectName("_VERSION")
        self.Result = QtWidgets.QLabel(self.centralwidget)
        self.Result.setGeometry(QtCore.QRect(300, 30, 500, 500))
        self.Result.setMinimumSize(QtCore.QSize(500, 500))
        self.Result.setAutoFillBackground(False)
        self.Result.setStyleSheet("background-color: rgb(255, 255, 255);\n"
                                  "border-style: outset;\n"
                                  "border-color: rgb(0, 0, 0);\n"
                                  "border-width: 5px;\n"
                                  "border-radius:15px;")
        self.Result.setText("")
        self.Result.setScaledContents(True)
        self.Result.setObjectName("Result")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 230, 281, 301))
        self.tabWidget.setStyleSheet("background-color: rgb(165, 165, 165);")
        self.tabWidget.setObjectName("tabWidget")
        self.Generalsettings = QtWidgets.QWidget()
        self.Generalsettings.setObjectName("Generalsettings")
        self._GENERATION_LABEL = QtWidgets.QLabel(self.Generalsettings)
        self._GENERATION_LABEL.setGeometry(QtCore.QRect(10, 10, 111, 21))
        font = QtGui.QFont()
        font.setFamily("SamsungOneUI")
        font.setPointSize(10)
        self._GENERATION_LABEL.setFont(font)
        self._GENERATION_LABEL.setStyleSheet("")
        self._GENERATION_LABEL.setObjectName("_GENERATION_LABEL")
        self._ZOOM_LABEL = QtWidgets.QLabel(self.Generalsettings)
        self._ZOOM_LABEL.setGeometry(QtCore.QRect(10, 60, 81, 16))
        font = QtGui.QFont()
        font.setFamily("SamsungOneUI")
        font.setPointSize(10)
        self._ZOOM_LABEL.setFont(font)
        self._ZOOM_LABEL.setObjectName("_ZOOM_LABEL")
        self._SIZE_LABEL = QtWidgets.QLabel(self.Generalsettings)
        self._SIZE_LABEL.setGeometry(QtCore.QRect(10, 100, 121, 16))
        font = QtGui.QFont()
        font.setFamily("SamsungOneUI")
        font.setPointSize(10)
        self._SIZE_LABEL.setFont(font)
        self._SIZE_LABEL.setObjectName("_SIZE_LABEL")
        self.layoutWidget = QtWidgets.QWidget(self.Generalsettings)
        self.layoutWidget.setGeometry(QtCore.QRect(160, 0, 111, 131))
        self.layoutWidget.setObjectName("layoutWidget")
        self.Default_change = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.Default_change.setContentsMargins(0, 0, 0, 0)
        self.Default_change.setObjectName("Default_change")
        self.Generation_ComboBox = QtWidgets.QComboBox(self.layoutWidget)
        self.Generation_ComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Generation_ComboBox.setObjectName("Generation_ComboBox")
        self.Generation_ComboBox.addItem("")
        self.Generation_ComboBox.addItem("")
        self.Generation_ComboBox.addItem("")
        self.Generation_ComboBox.addItem("")
        self.Default_change.addWidget(self.Generation_ComboBox)
        self.Zoom_ComboBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.Zoom_ComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Zoom_ComboBox.setMinimum(10)
        self.Zoom_ComboBox.setMaximum(500)
        self.Zoom_ComboBox.setSingleStep(10)
        self.Zoom_ComboBox.setProperty("value", 50)
        self.Zoom_ComboBox.setObjectName("Zoom_ComboBox")
        self.Default_change.addWidget(self.Zoom_ComboBox)
        self.Size_ComboBox = QtWidgets.QSpinBox(self.layoutWidget)
        self.Size_ComboBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.Size_ComboBox.setMinimum(100)
        self.Size_ComboBox.setMaximum(1000)
        self.Size_ComboBox.setSingleStep(100)
        self.Size_ComboBox.setProperty("value", 200)
        self.Size_ComboBox.setObjectName("Size_ComboBox")
        self.Default_change.addWidget(self.Size_ComboBox)
        self.FAQ = QtWidgets.QPushButton(self.Generalsettings)
        self.FAQ.setGeometry(QtCore.QRect(110, 240, 151, 31))
        self.FAQ.setStyleSheet("background-color: rgb(13, 13, 13);\n"
                               "font: 63 8pt \"Bahnschrift SemiBold\";\n"
                               "color:rgb(255, 255, 255);\n"
                               "border-style:outset;\n"
                               "border-width:4px;\n"
                               "border-radius:15px;\n"
                               "border-color:rgb(30, 30, 30)")
        self.FAQ.setObjectName("FAQ")
        self.tabWidget.addTab(self.Generalsettings, "")
        self.Forest_Biome_Settings = QtWidgets.QWidget()
        self.Forest_Biome_Settings.setObjectName("Forest_Biome_Settings")
        self.___SAND = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.___SAND.setGeometry(QtCore.QRect(10, 70, 51, 16))
        self.___SAND.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                   "color:rgb(255, 255, 255);")
        self.___SAND.setObjectName("___SAND")
        self.___LEVELS = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.___LEVELS.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.___LEVELS.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
                                     "color:rgb(255, 255, 255);")
        self.___LEVELS.setObjectName("___LEVELS")
        self.___FOREST = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.___FOREST.setGeometry(QtCore.QRect(10, 110, 41, 16))
        self.___FOREST.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                     "color:rgb(255, 255, 255);")
        self.___FOREST.setObjectName("___FOREST")
        self.___DEEP_FOREST = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.___DEEP_FOREST.setGeometry(QtCore.QRect(10, 150, 81, 16))
        self.___DEEP_FOREST.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                          "color:rgb(255, 255, 255);")
        self.___DEEP_FOREST.setObjectName("___DEEP_FOREST")
        self.___WATER = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.___WATER.setGeometry(QtCore.QRect(10, 30, 41, 16))
        self.___WATER.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                    "color:rgb(255, 255, 255);")
        self.___WATER.setObjectName("___WATER")
        self.___MOUNTAINS = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.___MOUNTAINS.setGeometry(QtCore.QRect(10, 190, 41, 16))
        self.___MOUNTAINS.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                        "color:rgb(255, 255, 255);")
        self.___MOUNTAINS.setObjectName("___MOUNTAINS")
        self.forest_label_water = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.forest_label_water.setGeometry(QtCore.QRect(210, 30, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.forest_label_water.setFont(font)
        self.forest_label_water.setObjectName("forest_label_water")
        self.forest_label_sand = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.forest_label_sand.setGeometry(QtCore.QRect(210, 70, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.forest_label_sand.setFont(font)
        self.forest_label_sand.setObjectName("forest_label_sand")
        self.forest_label_forest = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.forest_label_forest.setGeometry(QtCore.QRect(210, 110, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.forest_label_forest.setFont(font)
        self.forest_label_forest.setObjectName("forest_label_forest")
        self.forest_label_deepf = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.forest_label_deepf.setGeometry(QtCore.QRect(210, 150, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.forest_label_deepf.setFont(font)
        self.forest_label_deepf.setObjectName("forest_label_deepf")
        self.forest_label_mountains = QtWidgets.QLabel(self.Forest_Biome_Settings)
        self.forest_label_mountains.setGeometry(QtCore.QRect(210, 190, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.forest_label_mountains.setFont(font)
        self.forest_label_mountains.setObjectName("forest_label_mountains")
        self.layoutWidget1 = QtWidgets.QWidget(self.Forest_Biome_Settings)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 30, 271, 221))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.ForestLayout = QtWidgets.QGridLayout(self.layoutWidget1)
        self.ForestLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.ForestLayout.setContentsMargins(0, 0, 0, 0)
        self.ForestLayout.setObjectName("ForestLayout")
        self.Forest_Slider_deepf = QtWidgets.QSlider(self.layoutWidget1)
        self.Forest_Slider_deepf.setEnabled(True)
        self.Forest_Slider_deepf.setStyleSheet("QSlider::groove:horizontal {\n"
                                               "    border: 1px solid #999999;\n"
                                               "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                               "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                               "    margin: 2px 0;\n"
                                               "}\n"
                                               "\n"
                                               "QSlider::handle:horizontal {\n"
                                               "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                               "    border: 1px solid #5c5c5c;\n"
                                               "    width: 18px;\n"
                                               "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                               "    border-radius: 3px;\n"
                                               "}\n"
                                               "Qslider:disabled{\n"
                                               "    background-color: rgb(47, 47, 47);\n"
                                               "}")
        self.Forest_Slider_deepf.setMinimum(130)
        self.Forest_Slider_deepf.setMaximum(255)
        self.Forest_Slider_deepf.setProperty("value", 150)
        self.Forest_Slider_deepf.setOrientation(QtCore.Qt.Horizontal)
        self.Forest_Slider_deepf.setObjectName("Forest_Slider_deepf")
        self.ForestLayout.addWidget(self.Forest_Slider_deepf, 3, 0, 1, 1)
        self.Forest_checkBox_sand = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Forest_checkBox_sand.setStyleSheet("")
        self.Forest_checkBox_sand.setText("")
        self.Forest_checkBox_sand.setChecked(True)
        self.Forest_checkBox_sand.setTristate(False)
        self.Forest_checkBox_sand.setObjectName("Forest_checkBox_sand")
        self.ForestLayout.addWidget(self.Forest_checkBox_sand, 1, 1, 1, 1)
        self.Forest_Slider_mountains = QtWidgets.QSlider(self.layoutWidget1)
        self.Forest_Slider_mountains.setEnabled(True)
        self.Forest_Slider_mountains.setStyleSheet("QSlider::groove:horizontal {\n"
                                                   "    border: 1px solid #999999;\n"
                                                   "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                                   "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                                   "    margin: 2px 0;\n"
                                                   "}\n"
                                                   "\n"
                                                   "QSlider::handle:horizontal {\n"
                                                   "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                                   "    border: 1px solid #5c5c5c;\n"
                                                   "    width: 18px;\n"
                                                   "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                                   "    border-radius: 3px;\n"
                                                   "}\n"
                                                   "Qslider:disabled{\n"
                                                   "    background-color: rgb(47, 47, 47);\n"
                                                   "}")
        self.Forest_Slider_mountains.setMinimum(150)
        self.Forest_Slider_mountains.setMaximum(255)
        self.Forest_Slider_mountains.setProperty("value", 180)
        self.Forest_Slider_mountains.setOrientation(QtCore.Qt.Horizontal)
        self.Forest_Slider_mountains.setObjectName("Forest_Slider_mountains")
        self.ForestLayout.addWidget(self.Forest_Slider_mountains, 4, 0, 1, 1)
        self.Forest_Slider_sand = QtWidgets.QSlider(self.layoutWidget1)
        self.Forest_Slider_sand.setEnabled(True)
        self.Forest_Slider_sand.setStyleSheet("QSlider::groove:horizontal {\n"
                                              "    border: 1px solid #999999;\n"
                                              "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                              "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                              "    margin: 2px 0;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::handle:horizontal {\n"
                                              "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                              "    border: 1px solid #5c5c5c;\n"
                                              "    width: 18px;\n"
                                              "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                              "    border-radius: 3px;\n"
                                              "}\n"
                                              "Qslider:disabled{\n"
                                              "    background-color: rgb(47, 47, 47);\n"
                                              "}")
        self.Forest_Slider_sand.setMinimum(110)
        self.Forest_Slider_sand.setMaximum(255)
        self.Forest_Slider_sand.setProperty("value", 113)
        self.Forest_Slider_sand.setOrientation(QtCore.Qt.Horizontal)
        self.Forest_Slider_sand.setObjectName("Forest_Slider_sand")
        self.ForestLayout.addWidget(self.Forest_Slider_sand, 1, 0, 1, 1)
        self.Forest_checkBox_water = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Forest_checkBox_water.setStyleSheet("QCheckBox::indicator {\n"
                                                 "    width: 13px;\n"
                                                 "    height: 13px;\n"
                                                 "}\n"
                                                 "")
        self.Forest_checkBox_water.setText("")
        self.Forest_checkBox_water.setChecked(True)
        self.Forest_checkBox_water.setObjectName("Forest_checkBox_water")
        self.ForestLayout.addWidget(self.Forest_checkBox_water, 0, 1, 1, 1)
        self.Forest_checkBox_mountain = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Forest_checkBox_mountain.setStyleSheet("QCheckBox::indicator {\n"
                                                    "    width: 13px;\n"
                                                    "    height: 13px;\n"
                                                    "}\n"
                                                    "")
        self.Forest_checkBox_mountain.setText("")
        self.Forest_checkBox_mountain.setChecked(True)
        self.Forest_checkBox_mountain.setObjectName("Forest_checkBox_mountain")
        self.ForestLayout.addWidget(self.Forest_checkBox_mountain, 4, 1, 1, 1)
        self.Forest_Slider_forest = QtWidgets.QSlider(self.layoutWidget1)
        self.Forest_Slider_forest.setEnabled(True)
        self.Forest_Slider_forest.setStyleSheet("QSlider::groove:horizontal {\n"
                                                "    border: 1px solid #999999;\n"
                                                "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                                "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                                "    margin: 2px 0;\n"
                                                "}\n"
                                                "\n"
                                                "QSlider::handle:horizontal {\n"
                                                "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                                "    border: 1px solid #5c5c5c;\n"
                                                "    width: 18px;\n"
                                                "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                                "    border-radius: 3px;\n"
                                                "}\n"
                                                "Qslider:disabled{\n"
                                                "    background-color: rgb(47, 47, 47);\n"
                                                "}")
        self.Forest_Slider_forest.setMinimum(113)
        self.Forest_Slider_forest.setMaximum(255)
        self.Forest_Slider_forest.setProperty("value", 130)
        self.Forest_Slider_forest.setOrientation(QtCore.Qt.Horizontal)
        self.Forest_Slider_forest.setObjectName("Forest_Slider_forest")
        self.ForestLayout.addWidget(self.Forest_Slider_forest, 2, 0, 1, 1)
        self.Forest_Slider_water = QtWidgets.QSlider(self.layoutWidget1)
        self.Forest_Slider_water.setEnabled(True)
        self.Forest_Slider_water.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Forest_Slider_water.setAutoFillBackground(False)
        self.Forest_Slider_water.setStyleSheet("QSlider::groove:horizontal {\n"
                                               "    border: 1px solid #999999;\n"
                                               "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                               "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                               "    margin: 2px 0;\n"
                                               "}\n"
                                               "\n"
                                               "QSlider::handle:horizontal {\n"
                                               "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                               "    border: 1px solid #5c5c5c;\n"
                                               "    width: 18px;\n"
                                               "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                               "    border-radius: 3px;\n"
                                               "}\n"
                                               "Qslider:disabled{\n"
                                               "    background-color: rgb(47, 47, 47);\n"
                                               "}")
        self.Forest_Slider_water.setMinimum(100)
        self.Forest_Slider_water.setMaximum(255)
        self.Forest_Slider_water.setSingleStep(1)
        self.Forest_Slider_water.setProperty("value", 110)
        self.Forest_Slider_water.setSliderPosition(110)
        self.Forest_Slider_water.setOrientation(QtCore.Qt.Horizontal)
        self.Forest_Slider_water.setInvertedAppearance(False)
        self.Forest_Slider_water.setInvertedControls(False)
        self.Forest_Slider_water.setObjectName("Forest_Slider_water")
        self.ForestLayout.addWidget(self.Forest_Slider_water, 0, 0, 1, 1)
        self.Forest_checkBox_deepf = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Forest_checkBox_deepf.setStyleSheet("QCheckBox::indicator {\n"
                                                 "    width: 13px;\n"
                                                 "    height: 13px;\n"
                                                 "}\n"
                                                 "")
        self.Forest_checkBox_deepf.setText("")
        self.Forest_checkBox_deepf.setChecked(True)
        self.Forest_checkBox_deepf.setObjectName("Forest_checkBox_deepf")
        self.ForestLayout.addWidget(self.Forest_checkBox_deepf, 3, 1, 1, 1)
        self.Forest_checkBox_forest = QtWidgets.QCheckBox(self.layoutWidget1)
        self.Forest_checkBox_forest.setStyleSheet("QCheckBox::indicator {\n"
                                                  "    width: 13px;\n"
                                                  "    height: 13px;\n"
                                                  "}\n"
                                                  "")
        self.Forest_checkBox_forest.setText("")
        self.Forest_checkBox_forest.setChecked(True)
        self.Forest_checkBox_forest.setObjectName("Forest_checkBox_forest")
        self.ForestLayout.addWidget(self.Forest_checkBox_forest, 2, 1, 1, 1)
        self.Forest_Slider_forest.raise_()
        self.Forest_Slider_mountains.raise_()
        self.Forest_Slider_sand.raise_()
        self.Forest_Slider_water.raise_()
        self.Forest_Slider_deepf.raise_()
        self.Forest_checkBox_forest.raise_()
        self.Forest_checkBox_sand.raise_()
        self.Forest_checkBox_water.raise_()
        self.Forest_checkBox_deepf.raise_()
        self.Forest_checkBox_mountain.raise_()
        self.layoutWidget.raise_()
        self.forest_label_sand.raise_()
        self.___LEVELS.raise_()
        self.forest_label_forest.raise_()
        self.___DEEP_FOREST.raise_()
        self.___SAND.raise_()
        self.___WATER.raise_()
        self.forest_label_mountains.raise_()
        self.forest_label_water.raise_()
        self.___MOUNTAINS.raise_()
        self.forest_label_deepf.raise_()
        self.___FOREST.raise_()
        self.tabWidget.addTab(self.Forest_Biome_Settings, "")
        self.Desert_Biome_Settings = QtWidgets.QWidget()
        self.Desert_Biome_Settings.setObjectName("Desert_Biome_Settings")
        self.layoutWidget_2 = QtWidgets.QWidget(self.Desert_Biome_Settings)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 30, 271, 221))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.DesertLayout = QtWidgets.QGridLayout(self.layoutWidget_2)
        self.DesertLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.DesertLayout.setContentsMargins(0, 0, 0, 0)
        self.DesertLayout.setObjectName("DesertLayout")
        self.Desert_checkBox_sand = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.Desert_checkBox_sand.setStyleSheet("")
        self.Desert_checkBox_sand.setText("")
        self.Desert_checkBox_sand.setChecked(True)
        self.Desert_checkBox_sand.setTristate(False)
        self.Desert_checkBox_sand.setObjectName("Desert_checkBox_sand")
        self.DesertLayout.addWidget(self.Desert_checkBox_sand, 1, 1, 1, 1)
        self.Desert_Slider_lowsand = QtWidgets.QSlider(self.layoutWidget_2)
        self.Desert_Slider_lowsand.setEnabled(True)
        self.Desert_Slider_lowsand.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Desert_Slider_lowsand.setAutoFillBackground(False)
        self.Desert_Slider_lowsand.setStyleSheet("QSlider::groove:horizontal {\n"
                                                 "    border: 1px solid #999999;\n"
                                                 "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                                 "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                                 "    margin: 2px 0;\n"
                                                 "}\n"
                                                 "\n"
                                                 "QSlider::handle:horizontal {\n"
                                                 "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                                 "    border: 1px solid #5c5c5c;\n"
                                                 "    width: 18px;\n"
                                                 "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                                 "    border-radius: 3px;\n"
                                                 "}\n"
                                                 "Qslider:disabled{\n"
                                                 "    background-color: rgb(47, 47, 47);\n"
                                                 "}")
        self.Desert_Slider_lowsand.setMinimum(100)
        self.Desert_Slider_lowsand.setMaximum(255)
        self.Desert_Slider_lowsand.setSingleStep(1)
        self.Desert_Slider_lowsand.setProperty("value", 125)
        self.Desert_Slider_lowsand.setSliderPosition(125)
        self.Desert_Slider_lowsand.setOrientation(QtCore.Qt.Horizontal)
        self.Desert_Slider_lowsand.setInvertedAppearance(False)
        self.Desert_Slider_lowsand.setInvertedControls(False)
        self.Desert_Slider_lowsand.setObjectName("Desert_Slider_lowsand")
        self.DesertLayout.addWidget(self.Desert_Slider_lowsand, 0, 0, 1, 1)
        self.Desert_Slider_sand = QtWidgets.QSlider(self.layoutWidget_2)
        self.Desert_Slider_sand.setEnabled(True)
        self.Desert_Slider_sand.setStyleSheet("QSlider::groove:horizontal {\n"
                                              "    border: 1px solid #999999;\n"
                                              "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                              "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                              "    margin: 2px 0;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::handle:horizontal {\n"
                                              "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                              "    border: 1px solid #5c5c5c;\n"
                                              "    width: 18px;\n"
                                              "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                              "    border-radius: 3px;\n"
                                              "}\n"
                                              "Qslider:disabled{\n"
                                              "    background-color: rgb(47, 47, 47);\n"
                                              "}")
        self.Desert_Slider_sand.setMinimum(126)
        self.Desert_Slider_sand.setMaximum(255)
        self.Desert_Slider_sand.setProperty("value", 150)
        self.Desert_Slider_sand.setOrientation(QtCore.Qt.Horizontal)
        self.Desert_Slider_sand.setObjectName("Desert_Slider_sand")
        self.DesertLayout.addWidget(self.Desert_Slider_sand, 1, 0, 1, 1)
        self.Desert_Slider_sand_hills = QtWidgets.QSlider(self.layoutWidget_2)
        self.Desert_Slider_sand_hills.setEnabled(True)
        self.Desert_Slider_sand_hills.setStyleSheet("QSlider::groove:horizontal {\n"
                                                    "    border: 1px solid #999999;\n"
                                                    "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                                    "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                                    "    margin: 2px 0;\n"
                                                    "}\n"
                                                    "\n"
                                                    "QSlider::handle:horizontal {\n"
                                                    "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                                    "    border: 1px solid #5c5c5c;\n"
                                                    "    width: 18px;\n"
                                                    "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                                    "    border-radius: 3px;\n"
                                                    "}\n"
                                                    "Qslider:disabled{\n"
                                                    "    background-color: rgb(47, 47, 47);\n"
                                                    "}")
        self.Desert_Slider_sand_hills.setMinimum(151)
        self.Desert_Slider_sand_hills.setMaximum(255)
        self.Desert_Slider_sand_hills.setProperty("value", 190)
        self.Desert_Slider_sand_hills.setOrientation(QtCore.Qt.Horizontal)
        self.Desert_Slider_sand_hills.setObjectName("Desert_Slider_sand_hills")
        self.DesertLayout.addWidget(self.Desert_Slider_sand_hills, 2, 0, 1, 1)
        self.Desert_checkBox_sand_hills = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.Desert_checkBox_sand_hills.setStyleSheet("QCheckBox::indicator {\n"
                                                      "    width: 13px;\n"
                                                      "    height: 13px;\n"
                                                      "}\n"
                                                      "")
        self.Desert_checkBox_sand_hills.setText("")
        self.Desert_checkBox_sand_hills.setChecked(True)
        self.Desert_checkBox_sand_hills.setObjectName("Desert_checkBox_sand_hills")
        self.DesertLayout.addWidget(self.Desert_checkBox_sand_hills, 2, 1, 1, 1)
        self.Desert_checkBox_lowsand = QtWidgets.QCheckBox(self.layoutWidget_2)
        self.Desert_checkBox_lowsand.setStyleSheet("QCheckBox::indicator {\n"
                                                   "    width: 13px;\n"
                                                   "    height: 13px;\n"
                                                   "}\n"
                                                   "")
        self.Desert_checkBox_lowsand.setText("")
        self.Desert_checkBox_lowsand.setChecked(True)
        self.Desert_checkBox_lowsand.setObjectName("Desert_checkBox_lowsand")
        self.DesertLayout.addWidget(self.Desert_checkBox_lowsand, 0, 1, 1, 1)
        self.___SAND_lv1 = QtWidgets.QLabel(self.Desert_Biome_Settings)
        self.___SAND_lv1.setGeometry(QtCore.QRect(10, 40, 81, 16))
        self.___SAND_lv1.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                       "color:rgb(255, 255, 255);")
        self.___SAND_lv1.setObjectName("___SAND_lv1")
        self.___SAND_lv2 = QtWidgets.QLabel(self.Desert_Biome_Settings)
        self.___SAND_lv2.setGeometry(QtCore.QRect(10, 100, 121, 16))
        self.___SAND_lv2.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                       "color:rgb(255, 255, 255);")
        self.___SAND_lv2.setObjectName("___SAND_lv2")
        self.___SAND_HILLS = QtWidgets.QLabel(self.Desert_Biome_Settings)
        self.___SAND_HILLS.setGeometry(QtCore.QRect(10, 170, 111, 16))
        self.___SAND_HILLS.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                         "color:rgb(255, 255, 255);")
        self.___SAND_HILLS.setObjectName("___SAND_HILLS")
        self.___LEVELS_D = QtWidgets.QLabel(self.Desert_Biome_Settings)
        self.___LEVELS_D.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.___LEVELS_D.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
                                       "color:rgb(255, 255, 255);")
        self.___LEVELS_D.setObjectName("___LEVELS_D")
        self.Desert_label_sand_hills = QtWidgets.QLabel(self.Desert_Biome_Settings)
        self.Desert_label_sand_hills.setGeometry(QtCore.QRect(210, 170, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Desert_label_sand_hills.setFont(font)
        self.Desert_label_sand_hills.setObjectName("Desert_label_sand_hills")
        self.Desert_label_sandlv1 = QtWidgets.QLabel(self.Desert_Biome_Settings)
        self.Desert_label_sandlv1.setGeometry(QtCore.QRect(210, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Desert_label_sandlv1.setFont(font)
        self.Desert_label_sandlv1.setObjectName("Desert_label_sandlv1")
        self.Desert_label_sandlv2 = QtWidgets.QLabel(self.Desert_Biome_Settings)
        self.Desert_label_sandlv2.setGeometry(QtCore.QRect(210, 110, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Desert_label_sandlv2.setFont(font)
        self.Desert_label_sandlv2.setObjectName("Desert_label_sandlv2")
        self.tabWidget.addTab(self.Desert_Biome_Settings, "")
        self.Frost_Biome_Settings = QtWidgets.QWidget()
        self.Frost_Biome_Settings.setObjectName("Frost_Biome_Settings")
        self.Frost___SNOW = QtWidgets.QLabel(self.Frost_Biome_Settings)
        self.Frost___SNOW.setGeometry(QtCore.QRect(10, 100, 51, 16))
        self.Frost___SNOW.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                        "color:rgb(255, 255, 255);")
        self.Frost___SNOW.setObjectName("Frost___SNOW")
        self.layoutWidget_6 = QtWidgets.QWidget(self.Frost_Biome_Settings)
        self.layoutWidget_6.setGeometry(QtCore.QRect(0, 30, 271, 221))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.FrostLayout = QtWidgets.QGridLayout(self.layoutWidget_6)
        self.FrostLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.FrostLayout.setContentsMargins(0, 0, 0, 0)
        self.FrostLayout.setObjectName("FrostLayout")
        self.Frost_Slider_Forest = QtWidgets.QSlider(self.layoutWidget_6)
        self.Frost_Slider_Forest.setEnabled(True)
        self.Frost_Slider_Forest.setStyleSheet("QSlider::groove:horizontal {\n"
                                               "    border: 1px solid #999999;\n"
                                               "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                               "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                               "    margin: 2px 0;\n"
                                               "}\n"
                                               "\n"
                                               "QSlider::handle:horizontal {\n"
                                               "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                               "    border: 1px solid #5c5c5c;\n"
                                               "    width: 18px;\n"
                                               "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                               "    border-radius: 3px;\n"
                                               "}\n"
                                               "Qslider:disabled{\n"
                                               "    background-color: rgb(47, 47, 47);\n"
                                               "}")
        self.Frost_Slider_Forest.setMinimum(141)
        self.Frost_Slider_Forest.setMaximum(255)
        self.Frost_Slider_Forest.setProperty("value", 175)
        self.Frost_Slider_Forest.setOrientation(QtCore.Qt.Horizontal)
        self.Frost_Slider_Forest.setObjectName("Frost_Slider_Forest")
        self.FrostLayout.addWidget(self.Frost_Slider_Forest, 2, 0, 1, 1)
        self.Frost_checkBox_snow = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.Frost_checkBox_snow.setStyleSheet("")
        self.Frost_checkBox_snow.setText("")
        self.Frost_checkBox_snow.setChecked(True)
        self.Frost_checkBox_snow.setTristate(False)
        self.Frost_checkBox_snow.setObjectName("Frost_checkBox_snow")
        self.FrostLayout.addWidget(self.Frost_checkBox_snow, 1, 1, 1, 1)
        self.Frost_Slider_water = QtWidgets.QSlider(self.layoutWidget_6)
        self.Frost_Slider_water.setEnabled(True)
        self.Frost_Slider_water.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Frost_Slider_water.setAutoFillBackground(False)
        self.Frost_Slider_water.setStyleSheet("QSlider::groove:horizontal {\n"
                                              "    border: 1px solid #999999;\n"
                                              "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                              "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                              "    margin: 2px 0;\n"
                                              "}\n"
                                              "\n"
                                              "QSlider::handle:horizontal {\n"
                                              "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                              "    border: 1px solid #5c5c5c;\n"
                                              "    width: 18px;\n"
                                              "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                              "    border-radius: 3px;\n"
                                              "}\n"
                                              "Qslider:disabled{\n"
                                              "    background-color: rgb(47, 47, 47);\n"
                                              "}")
        self.Frost_Slider_water.setMinimum(100)
        self.Frost_Slider_water.setMaximum(255)
        self.Frost_Slider_water.setSingleStep(1)
        self.Frost_Slider_water.setProperty("value", 125)
        self.Frost_Slider_water.setSliderPosition(125)
        self.Frost_Slider_water.setOrientation(QtCore.Qt.Horizontal)
        self.Frost_Slider_water.setInvertedAppearance(False)
        self.Frost_Slider_water.setInvertedControls(False)
        self.Frost_Slider_water.setObjectName("Frost_Slider_water")
        self.FrostLayout.addWidget(self.Frost_Slider_water, 0, 0, 1, 1)
        self.Frost_Slider_snow = QtWidgets.QSlider(self.layoutWidget_6)
        self.Frost_Slider_snow.setEnabled(True)
        self.Frost_Slider_snow.setStyleSheet("QSlider::groove:horizontal {\n"
                                             "    border: 1px solid #999999;\n"
                                             "    height: 8px; /* the groove expands to the size of the slider by default. by giving it a height, it has a fixed size */\n"
                                             "    background: qlineargradient(x1:0, y1:0, x2:0, y2:1, stop:0 #B1B1B1, stop:1 #c4c4c4);\n"
                                             "    margin: 2px 0;\n"
                                             "}\n"
                                             "\n"
                                             "QSlider::handle:horizontal {\n"
                                             "    background: qlineargradient(x1:0, y1:0, x2:1, y2:1, stop:0 #b4b4b4, stop:1 #8f8f8f);\n"
                                             "    border: 1px solid #5c5c5c;\n"
                                             "    width: 18px;\n"
                                             "    margin: -2px 0; /* handle is placed by default on the contents rect of the groove. Expand outside the groove */\n"
                                             "    border-radius: 3px;\n"
                                             "}\n"
                                             "Qslider:disabled{\n"
                                             "    background-color: rgb(47, 47, 47);\n"
                                             "}")
        self.Frost_Slider_snow.setMinimum(126)
        self.Frost_Slider_snow.setMaximum(255)
        self.Frost_Slider_snow.setProperty("value", 140)
        self.Frost_Slider_snow.setOrientation(QtCore.Qt.Horizontal)
        self.Frost_Slider_snow.setObjectName("Frost_Slider_snow")
        self.FrostLayout.addWidget(self.Frost_Slider_snow, 1, 0, 1, 1)
        self.Frost_checkBox_water = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.Frost_checkBox_water.setStyleSheet("QCheckBox::indicator {\n"
                                                "    width: 13px;\n"
                                                "    height: 13px;\n"
                                                "}\n"
                                                "")
        self.Frost_checkBox_water.setText("")
        self.Frost_checkBox_water.setChecked(True)
        self.Frost_checkBox_water.setObjectName("Frost_checkBox_water")
        self.FrostLayout.addWidget(self.Frost_checkBox_water, 0, 1, 1, 1)
        self.Frost_checkBox_forest = QtWidgets.QCheckBox(self.layoutWidget_6)
        self.Frost_checkBox_forest.setStyleSheet("QCheckBox::indicator {\n"
                                                 "    width: 13px;\n"
                                                 "    height: 13px;\n"
                                                 "}\n"
                                                 "")
        self.Frost_checkBox_forest.setText("")
        self.Frost_checkBox_forest.setChecked(True)
        self.Frost_checkBox_forest.setObjectName("Frost_checkBox_forest")
        self.FrostLayout.addWidget(self.Frost_checkBox_forest, 2, 1, 1, 1)
        self.Frost___LEVELS = QtWidgets.QLabel(self.Frost_Biome_Settings)
        self.Frost___LEVELS.setGeometry(QtCore.QRect(10, 0, 71, 21))
        self.Frost___LEVELS.setStyleSheet("font: 63 14pt \"Bahnschrift SemiBold\";\n"
                                          "color:rgb(255, 255, 255);")
        self.Frost___LEVELS.setObjectName("Frost___LEVELS")
        self.Frost___WATER = QtWidgets.QLabel(self.Frost_Biome_Settings)
        self.Frost___WATER.setGeometry(QtCore.QRect(10, 40, 41, 16))
        self.Frost___WATER.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                         "color:rgb(255, 255, 255);")
        self.Frost___WATER.setObjectName("Frost___WATER")
        self.Frost_label_snow_hills = QtWidgets.QLabel(self.Frost_Biome_Settings)
        self.Frost_label_snow_hills.setGeometry(QtCore.QRect(210, 170, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Frost_label_snow_hills.setFont(font)
        self.Frost_label_snow_hills.setObjectName("Frost_label_snow_hills")
        self.Frost_label_water = QtWidgets.QLabel(self.Frost_Biome_Settings)
        self.Frost_label_water.setGeometry(QtCore.QRect(210, 50, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Frost_label_water.setFont(font)
        self.Frost_label_water.setObjectName("Frost_label_water")
        self.Frost_label_snow = QtWidgets.QLabel(self.Frost_Biome_Settings)
        self.Frost_label_snow.setGeometry(QtCore.QRect(210, 110, 47, 13))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.Frost_label_snow.setFont(font)
        self.Frost_label_snow.setObjectName("Frost_label_snow")
        self.Frost___Forest = QtWidgets.QLabel(self.Frost_Biome_Settings)
        self.Frost___Forest.setGeometry(QtCore.QRect(10, 160, 101, 16))
        self.Frost___Forest.setStyleSheet("font: 63 10pt \"Bahnschrift SemiBold\";\n"
                                          "color:rgb(255, 255, 255);")
        self.Frost___Forest.setObjectName("Frost___Forest")
        self.layoutWidget_6.raise_()
        self.Frost___LEVELS.raise_()
        self.Frost___WATER.raise_()
        self.Frost_label_snow_hills.raise_()
        self.Frost_label_water.raise_()
        self.Frost_label_snow.raise_()
        self.Frost___SNOW.raise_()
        self.Frost___Forest.raise_()
        self.tabWidget.addTab(self.Frost_Biome_Settings, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.___SAND.setBuddy(self.Forest_checkBox_sand)
        self.___FOREST.setBuddy(self.Forest_checkBox_forest)
        self.___DEEP_FOREST.setBuddy(self.Forest_checkBox_deepf)
        self.___WATER.setBuddy(self.Forest_checkBox_water)
        self.___MOUNTAINS.setBuddy(self.Forest_checkBox_deepf)
        self.___SAND_lv1.setBuddy(self.Forest_checkBox_water)
        self.___SAND_lv2.setBuddy(self.Forest_checkBox_sand)
        self.___SAND_HILLS.setBuddy(self.Forest_checkBox_forest)
        self.Frost___SNOW.setBuddy(self.Forest_checkBox_sand)
        self.Frost___WATER.setBuddy(self.Forest_checkBox_water)
        self.Frost___Forest.setBuddy(self.Forest_checkBox_forest)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.Forest_Slider_deepf.valueChanged['int'].connect(self.forest_label_deepf.setNum)
        self.Forest_Slider_mountains.valueChanged['int'].connect(self.forest_label_mountains.setNum)
        self.Forest_Slider_water.valueChanged['int'].connect(self.forest_label_water.setNum)
        self.Forest_Slider_sand.valueChanged['int'].connect(self.forest_label_sand.setNum)
        self.Forest_Slider_forest.valueChanged['int'].connect(self.forest_label_forest.setNum)
        self.Desert_Slider_lowsand.valueChanged['int'].connect(self.Desert_label_sandlv1.setNum)
        self.Desert_Slider_sand.valueChanged['int'].connect(self.Desert_label_sandlv2.setNum)
        self.Desert_Slider_sand_hills.valueChanged['int'].connect(self.Desert_label_sand_hills.setNum)
        self.Frost_Slider_water.valueChanged['int'].connect(self.Frost_label_water.setNum)
        self.Frost_Slider_snow.valueChanged['int'].connect(self.Frost_label_snow.setNum)
        self.Frost_Slider_Forest.valueChanged['int'].connect(self.Frost_label_snow_hills.setNum)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Generator"))
        self.Generate_button.setText(_translate("MainWindow", "Сгенерировать"))
        self.Save_button.setText(_translate("MainWindow", "Сохранить"))
        self._VERSION.setText(_translate("MainWindow", "Generator V-1.0"))
        self._GENERATION_LABEL.setText(_translate("MainWindow", "Режим генерации:"))
        self._ZOOM_LABEL.setText(_translate("MainWindow", "Приближение"))
        self._SIZE_LABEL.setText(_translate("MainWindow", "Размер изображения"))
        self.Generation_ComboBox.setItemText(0, _translate("MainWindow", "Default"))
        self.Generation_ComboBox.setItemText(1, _translate("MainWindow", "Forest"))
        self.Generation_ComboBox.setItemText(2, _translate("MainWindow", "Desert"))
        self.Generation_ComboBox.setItemText(3, _translate("MainWindow", "Frost"))
        self.FAQ.setText(_translate("MainWindow", "Как это работает?"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Generalsettings), _translate("MainWindow", "General"))
        self.___SAND.setText(_translate("MainWindow", "Песок"))
        self.___LEVELS.setText(_translate("MainWindow", "Уровни"))
        self.___FOREST.setText(_translate("MainWindow", "Лес"))
        self.___DEEP_FOREST.setText(_translate("MainWindow", "Глубокий лес"))
        self.___WATER.setText(_translate("MainWindow", "Вода"))
        self.___MOUNTAINS.setText(_translate("MainWindow", "Горы"))
        self.forest_label_water.setText(_translate("MainWindow", "110"))
        self.forest_label_sand.setText(_translate("MainWindow", "113"))
        self.forest_label_forest.setText(_translate("MainWindow", "130"))
        self.forest_label_deepf.setText(_translate("MainWindow", "150"))
        self.forest_label_mountains.setText(_translate("MainWindow", "180"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Forest_Biome_Settings),
                                  _translate("MainWindow", "Forest"))
        self.___SAND_lv1.setText(_translate("MainWindow", "Песок"))
        self.___SAND_lv2.setText(_translate("MainWindow", "Песок уровень 2"))
        self.___SAND_HILLS.setText(_translate("MainWindow", "Песчаные холмы"))
        self.___LEVELS_D.setText(_translate("MainWindow", "Уровни"))
        self.Desert_label_sand_hills.setText(_translate("MainWindow", "190"))
        self.Desert_label_sandlv1.setText(_translate("MainWindow", "125"))
        self.Desert_label_sandlv2.setText(_translate("MainWindow", "150"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Desert_Biome_Settings),
                                  _translate("MainWindow", "Desert"))
        self.Frost___SNOW.setText(_translate("MainWindow", "Снег"))
        self.Frost___LEVELS.setText(_translate("MainWindow", "Уровни"))
        self.Frost___WATER.setText(_translate("MainWindow", "Вода"))
        self.Frost_label_snow_hills.setText(_translate("MainWindow", "175"))
        self.Frost_label_water.setText(_translate("MainWindow", "125"))
        self.Frost_label_snow.setText(_translate("MainWindow", "140"))
        self.Frost___Forest.setText(_translate("MainWindow", "Лес"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Frost_Biome_Settings), _translate("MainWindow", "Frost"))
